version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    env_file:
      - .env 
  drupal:
    depends_on:
      - db
    links: 
      - "db"
      - "db:my.db.server"
    image: drupal:latest
    ports:
      - "8000:80"
    volumes:
      - drupal_data:/var/www/html           
    restart: always
    environment:
      DRUPAL_DB_HOST: ${DRUPAL_DB_HOST}
      DRUPAL_DB_NAME: ${DRUPAL_DB_NAME}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}  
    env_file:
     - .env    
volumes:
  db_data: 
  drupal_data:
  # drupal_profiles:
  # drupal_themes:
  # drupal_sites: